### ISSUE TITLE
Crash while playing as Wanda with Cherry Forest's mod

### ISSUE THREAD

**Issue by ThunderDraconius** [penguin0616/insight#14]
![image](https://user-images.githubusercontent.com/34503062/133965808-9bfc7805-ea95-4c58-8091-4900ccab79d9.png)

Client log: [client_log.txt](https://github.com/penguin0616/Insight/files/7194016/client_log.txt)
Server log: [server_log.txt](https://github.com/penguin0616/Insight/files/7194019/server_log.txt)

I'm not sure how I got this error, it suddenly appeared. The only thing I know is that I was wandering around the cherry forest biome from Cherry Forest mod when this happened. I got this particular error while travelling around the cherry stone (the big tree). I can still interact with it after reconnecting to the server but after a day passed in-game, this error popped up.

I'm using Windows 10 64-bit, had already updated the game to the latest version. I'm the host and caves are enabled.

**Comment by penguin0616** [comment]
This is not really the fault of Insight.
This specific crash type usually occurs because a different mod has improperly implemented something networking-related, and Insight triggers the crash by touching the invalid setup in order to provide information.
To make matters worse, the error information is almost always inaccurate for this crash type, so it's very hard to figure out what mod is at fault. 
The only thing I can suggest is keeping your current mod set and slowly whittling down mod by mod (while keeping Insight active to trigger the crash) until you no longer get the crash.
