### ISSUE TITLE
Enquiry about extending Insight for other mods

### ISSUE THREAD

**Issue by HubertZhang** [penguin0616/insight#25]
First of all, thank you for this awesome mod!

I tried to display some extra information about mod prefabs. I write some `Describe` functions and add them to `Insight.prefab_descriptors` via `rawset(GLOBAL.Insight.descriptors, name, res)`.

And I wonder if it is a proper way to extend Insight mod? Would there be any API that mods can declare their `Insight` extension?

**Comment by penguin0616** [comment]
> First of all, thank you for this awesome mod!

Glad you like it!
Your approach is technically a valid way to add information. Though 
```lua
rawset(GLOBAL.Insight.descriptors, name, res)
```
should be
```lua
rawset(GLOBAL.Insight.prefab_descriptors, name, res)
```
for prefab descriptors.

The problem with adding API functions or whatnot is that Insight's priority is -9999. I set it to this so people would never have to worry about adding compatibility to Insight when it comes to things like hooking or upvalues. But that means they don't have access to Insight until later.
Ideally people should never have to set their priority below Insight in order to have access to the descriptors.

So one way that I suggest adding information can be found [here](https://steamcommunity.com/workshop/filedetails/discussion/2189004162/3076495389982409841/) but any approach that can interact with the ``Insight`` table should be a valid approach. Were there specific things you were looking to be able to do with Insight's functions?

**Comment by HubertZhang** [comment]
Wow, I didn't read this discussion before 😂.. They are exactly what I were looking for
